version: "3.7"

services:
  redis:
    image: redis:latest
    command: >
      /bin/bash -c "
      redis-server --save 60 1 --loglevel warning
      "
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  app:
    build: .
    command: >
      /bin/bash -c "
      sudo /usr/bin/python3 main.py
      "
    depends_on:
      - redis
    env_file:
      - .env
volumes:
  redis_data:
